client.go
client_test.go
common_test.go
pool_test.go

Implement logic to re-establish subscriptions if the connection is
closed (e.g. because the stream leader has failed over).

Make Subscribe more resilient

---

client.go

The client should not attempt to resubscribe on disconnect if it has
been explicitly closed.

Don't resubscribe if the client is closed

---

client.go

This should not be needed since there are StartAtX options instead.

Remove StartAt SubscriptionOption

---

message.go

This PR fixes liftbridge.AckInbox's documentation to reflect what is done within Liftbridge (current documentation states that no ack is sent if the inbox message parameter is not set, this is wrong: a random inbox is generated in that case).

Fix AckInbox documentation

---

client.go
go.mod
go.sum

This PR adds an RPC so that clients can ask for the deletion of a stream. All corresponding partitions will also be removed, as well as their persistent storage.
Note that Liftbridge clients that have subscribed to a stream that will get deleted do not receive any notification.

Stream deletion API

---

README.md
client.go
client_test.go
go.mod
go.sum
metadata.go

Related to issue https://github.com/liftbridge-io/liftbridge/issues/103
Add an opt-in option `ReadReplica` to indicate that the `SubscribeRequest` can be subscribed to an ISR replica.
The client, upon seeing `readReplica` option, will not try to get partition's leader address but instead, get server address of a partition's ISR replica.
https://github.com/liftbridge-io/liftbridge-api/pull/22

Add opt-in option to read from ISR replica

---

client.go
client_test.go

When FailedPrecondition error is sent on subscriber stream this
indicates the partition was paused.

Return ErrPartitionPaused when partition is paused

---

client.go
go.mod
go.sum

Liftbridge offers the option of pausing a stream (with some or all of its partitions) to reduce the amount of CPU and memory usage on idle streams. When that happens, every subscriber to a partition receives an error. Publishing to a paused partition will resume it, allowing it to function as before.
Our use-case includes a situation where we would like to read from a partition even if it is paused. It has to be resumed to do so, but we do not want to publish to it. This PR adds an option to the subscription request to allow it to resume a partition instead of returning an error.

Add an option to allow resuming a paused partition when subscribing

---

metadata.go
v2/metadata.go

This PR adds a function to access the stream map when fetching metadata. The current API only allows you to get a SteamInfo using a stream name.

Metadata: add a function to access the stream map

---

message.go

Publication ACKs currently return the stream offset the message was committed to, but not its timestamp. This PR adds this.

Add a timestamp to publication acks

---

v2/client.go
v2/client_test.go
v2/go.mod
v2/go.sum

This allows overriding clustering.min.insync.replicas for individual
streams.

Add MinISR StreamOption

---

v2/client_test.go
v2/common_test.go

The current test behavior stores mock responses as an array in the mock API struct
```golang
type mockAPI struct {
mu                        sync.Mutex
responses                 []interface{}
....
}
```
This does not differentiate the responses of different rpc endpoints. Thus, in order to simulate different scenarios, the order in which the mock responses are stored is important.
In my opinion, the mock API should be:
1. Deterministic : The rpc should returns mocked result consistently, regardless of how we store the mock responses' order
2. Idempotent: The mock endpoint can be hit multiple times and still expect to return same results. It would be a bit easier to debug tests
3. Isolate: responses of one mock rpc endpoint should not affect the mock response of other endpoint.
1. …

Use map to store mock responses in tests

---

v2/client.go
v2/client_test.go
v2/common_test.go
v2/metadata.go

Implement the rpc call for [`FetchPartitionMetadata`](https://github.com/liftbridge-io/liftbridge/blob/master/documentation/client_implementation.md#fetchpartitionmetadata)
Related [issues](https://github.com/liftbridge-io/go-liftbridge/issues/87)

Implement FetchPartitionMetadata 

---

v2/client_test.go
v2/metadata.go

This PR adds two missing getters for StreamInfo's name and subject.

Metadata: add missing getters for the stream name and subject

---

v2/client.go

I'm doing a bit of performance testing and could do with being able to configure the buffer sizes.

Expose GRPC read and write buffer sizes as client options

---

README.md
v2/client.go
v2/go.mod
v2/go.sum
v2/message.go

To support [Optimistic Concurrency Control](https://github.com/liftbridge-io/liftbridge/issues/54), the following changes are needed in the client : 
-  Add function to enable `OptimisticConcurrencyControl` on `CreateStream`. 
-  Add function to take `ExpectedOffset` as params on `Publish`
This PR is the prerequisite for https://github.com/liftbridge-io/liftbridge/pull/296

Add support for Optimistic Concurrency Control

---

v2/client.go
v2/client_test.go
v2/metadata.go

This adds a new `ConnectCtx` function that allows connecting using a context, so that the connection can be cancelled using a deadline other than the default gRPC one. The connection is only blocking if a context with a deadline has been provided.
This PR fixes https://github.com/liftbridge-io/go-liftbridge/issues/98.

Add a ConnectCtx function to initiate a connection using a context

---

go.sum
v2/go.mod
v2/go.sum
v2/metadata.go

When `FetchMetadata` is called, some fields in `PartitionInfo` are missing. This is because, when `metadata.Update(ctx)` is called, some metadata like `HighWatermark` isn't updated in `PartitionInfo`. This additional metadata is updated when `FetchPartitionMetadata()` is called. This PR updates the missing fields when `metadata.Update` is called. Let me know if I need to change something else.
P.S: This also updates the `liftbridge-api` version for the additional fields in proto for `PartitionInfo`.

Update missing metadata to PartitionInfo when metadata is updated

---

v2/client.go
v2/client_test.go

Without this change, headers are omitted from messages published to the
Liftbridge API.

Add headers to published messages

---

v2/brokers.go
v2/client.go
v2/client_test.go
v2/common_test.go

Make PublishAsync more resilient by attempting to reconnect the
PublishAsync streaming RPC if the connection is disrupted.

Make PublishAsync more resilient
